
CREATE TABLE Player
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NCHAR(256) NULL, 
    [Wins] INT NOT NULL DEFAULT 0, 
    [Losses] INT NOT NULL DEFAULT 0, 
    [Picture] IMAGE NULL
)

CREATE TABLE Class
(
	[Id] INT NOT NULL PRIMARY KEY,
    [Name] NCHAR(256) NULL, 
	[GoodTeam] BIT NOT NULL 
)

CREATE TABLE GameInstance
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Date] DATETIME NULL
)

CREATE TABLE Vote
(
	[Id] INT NOT NULL PRIMARY KEY,
	[PlayerId] INT NOT NULL FOREIGN KEY REFERENCES Player(Id),
	[GameId] INT NOT NULL FOREIGN KEY REFERENCES GameInstance(Id),
	[Quest] INT NOT NULL,
	[VoteTrack] INT NOT NULL,
	[Accept] BIT NOT NULL 
)

CREATE TABLE PlayerInstance
(
	[Id] INT NOT NULL PRIMARY KEY,
	[PlayerId] INT NOT NULL FOREIGN KEY REFERENCES Player(Id),
	[ClassId] INT NOT NULL FOREIGN KEY REFERENCES Class(Id),
	[GameInstanceId] INT NOT NULL FOREIGN KEY REFERENCES GameInstance(Id),
)

