
CREATE TABLE Players
(
    [Id] INT NOT NULL PRIMARY KEY, 
    [Name] NCHAR(256) NULL,
)

CREATE TABLE Characters
(
	[Id] INT NOT NULL PRIMARY KEY,
    [Name] NCHAR(256) NULL, 
	[GoodTeam] BIT NOT NULL 
)

CREATE TABLE GameInstances
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Date] DATETIME NULL
	[WinnerGood] BIT NOT NULL,
	[Assassinated] BIT NOT NULL,
)

CREATE TABLE Votes
(
	[Id] INT NOT NULL PRIMARY KEY,
	[PlayerId] INT NOT NULL FOREIGN KEY REFERENCES Players(Id),
	[GameId] INT NOT NULL FOREIGN KEY REFERENCES GameInstances(Id),
	[Quest] INT NOT NULL,
	[VoteTrack] INT NOT NULL,
	[Accept] BIT NOT NULL 
)

CREATE TABLE PlayerInstances
(
	[Id] INT NOT NULL PRIMARY KEY,
	[PlayerId] INT NOT NULL FOREIGN KEY REFERENCES Player(Id),
	[ClassId] INT NOT NULL FOREIGN KEY REFERENCES Class(Id),
	[GameInstanceId] INT NOT NULL FOREIGN KEY REFERENCES GameInstance(Id),
)

