//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivePlayer
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
