//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyVote
    {
        public int PlayerId { get; set; }
        public bool ApproveFlag { get; set; }
        public int PartyId { get; set; }
        public int QuestId { get; set; }
    
        public virtual Quest Quest { get; set; }
        public virtual ActivePlayer ActivePlayer { get; set; }
        public virtual Party Parties { get; set; }
    }
}
