//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public Quest()
        {
            this.QuestVotes = new HashSet<QuestVote>();
        }
    
        public int Id { get; set; }
        public int Stage { get; set; }
        public int VoteTrack { get; set; }
    
        public virtual ICollection<QuestVote> QuestVotes { get; set; }
    }
}
