//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvalonTracker.SerializableStrings", typeof(SerializableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyal Servant of Arthur.
        /// </summary>
        internal static string LoyalServantOfArthur {
            get {
                return ResourceManager.GetString("LoyalServantOfArthur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merlin.
        /// </summary>
        internal static string Merlin {
            get {
                return ResourceManager.GetString("Merlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minion of Mordred.
        /// </summary>
        internal static string MinionOfMordred {
            get {
                return ResourceManager.GetString("MinionOfMordred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordred.
        /// </summary>
        internal static string Mordred {
            get {
                return ResourceManager.GetString("Mordred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morgana.
        /// </summary>
        internal static string Morgana {
            get {
                return ResourceManager.GetString("Morgana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberon.
        /// </summary>
        internal static string Oberon {
            get {
                return ResourceManager.GetString("Oberon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percival.
        /// </summary>
        internal static string Percival {
            get {
                return ResourceManager.GetString("Percival", resourceCulture);
            }
        }
    }
}
